# Generated by Django 4.2.4 on 2023-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='buses',
            field=models.ManyToManyField(related_name='package_buses', to='travel.bus'),
        ),
    ]
