# Generated by Django 4.2.4 on 2023-08-16 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_category',
            field=models.IntegerField(choices=[(5, '5 Star'), (4, '4 Star'), (3, '3 Star'), (2, '2 Star'), (1, '1 Star')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.cartype'),
        ),
    ]
