# Generated by Django 4.2.6 on 2023-10-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desertsafari',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
