# Generated by Django 4.2.6 on 2023-11-08 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaAdventure',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='activity_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('adventure_type', models.CharField(blank=True, max_length=100)),
                ('equipment_rental', models.TextField(blank=True)),
                ('safety_guidelines', models.TextField(blank=True)),
                ('weight_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('age_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('available_dates', models.CharField(blank=True, max_length=100)),
                ('booking_options', models.TextField(blank=True)),
                ('inclusions', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='available_till',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='available_from',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='available_to',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AlterField(
            model_name='package',
            name='departure',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.CreateModel(
            name='SeaAdventureImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='sea_adventure_images/')),
                ('sea_adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.seaadventure')),
            ],
        ),
    ]
