# Generated by Django 4.2.6 on 2023-10-25 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_desertsafari_duration_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='activity_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('duration_hours', models.PositiveIntegerField()),
                ('age_limit', models.PositiveIntegerField()),
                ('includes_meals', models.BooleanField(default=False)),
                ('schedule', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('max_participants', models.PositiveIntegerField()),
                ('equipment_provided', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityTourImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='city_tour_images/')),
                ('city_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.citytour')),
            ],
        ),
    ]
