# Generated by Django 4.2.4 on 2023-08-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_hotelamenity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='rent',
            new_name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
