# Generated by Django 4.2.5 on 2023-09-23 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_busreservation_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='booking',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_till',
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='available_from',
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='available_to',
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='offer_images/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='departure',
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.car')),
            ],
        ),
    ]
