# Generated by Django 4.2.6 on 2023-11-10 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_bus_image_bus_name_busimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_till',
            field=models.DateField(default=datetime.date(2023, 11, 10)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='available_from',
            field=models.DateField(default=datetime.date(2023, 11, 10)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='available_to',
            field=models.DateField(default=datetime.date(2023, 11, 10)),
        ),
        migrations.AlterField(
            model_name='package',
            name='departure',
            field=models.DateField(default=datetime.date(2023, 11, 10)),
        ),
    ]
