# Generated by Django 4.2.4 on 2023-08-18 12:06

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_booking_id_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=8, max_length=10, prefix='', primary_key=True, serialize=False),
        ),
    ]
